### ISSUE TITLE
Mark rows of the test table if JSON has changed

### ISSUE THREAD

**Issue by cpsievert** [ropensci/plotly-test-table#7]
From the discussion started [here](https://github.com/ropensci/plotly/pull/178#commitcomment-10114303).

**Comment by tdhock** [comment]
workin on it

**Comment by tdhock** [comment]
just pushed some code which should list only the rows with differences in big.html files (currently by comparing the MD5 of png files).

TODO download the json and compare that too.

**Comment by cpsievert** [comment]
Hmm, I'm not by my computer, but I checked the most recent test table on my
phone and it looks like master is being compared with master

**Comment by cpsievert** [comment]
Thanks for making these changes @tdhock!

For some reason, the SHA1 doesn't match between the test table -- http://ropensci.github.io/plotly-test-table/tables/ef301b0e7c602b1cb1484f73426ac30dcbf24983/index.html

And the images that it links to --  http://ropensci.github.io/plotly-test-table/data/90c55a33b7939879d050f757f51687c2865c8e50/cookbook-axes-flevels.png

Also, looking at the most recent build, I see a bunch of `md5sum: No such file or directory` warnings. 
https://travis-ci.org/ropensci/plotly/builds/55330721#L2007

**Comment by tdhock** [comment]
just fixed a couple of bugs in table.R and the table should be re-building now on travis...

**Comment by tdhock** [comment]
also, it is totally normal to have md5sum no such file or directory warnings. this happens for every json file (which don't exist yet since I don't download them yet).

**Comment by tdhock** [comment]
seems to be working now

for example the ribbon branch big.html file only shows the ribbon rows

http://ropensci.github.io/plotly-test-table/tables/ef301b0e7c602b1cb1484f73426ac30dcbf24983/big.html

**Comment by maelle** [comment]
⛔️ [MOVED] to https://github.com/cpsievert/plotly-test-table
