### ISSUE TITLE
still used?

### ISSUE THREAD

**Issue by maelle** [ropensci/plotly-test-table#8]
@cpsievert :wave: is this repo still used or should it get a badge e.g. http://www.repostatus.org/#inactive and be archived? 😺

**Comment by cpsievert** [comment]
Hi @maelle, yes, looks like I moved everything to https://github.com/cpsievert/plotly-test-table, so go ahead, thanks!

**Comment by maelle** [comment]
Thanks!

**Comment by maelle** [comment]
I'll add a _moved_ badge which should be more appropriate.
